version: "3.9"
services:
  api:
    build: ./backend
    container_name: historyai-api
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - redis
    volumes:
      - ./output:/app/output
    restart: always

  worker:
    build: ./backend
    container_name: historyai-worker
    command: python /app/worker/worker.py
    env_file:
      - .env
    depends_on:
      - redis
    volumes:
      - ./output:/app/output
    restart: always

  redis:
    image: redis:7-alpine
    container_name: historyai-redis
    restart: always
